query CartInput {
  cart {
    buyerIdentity {
      email
      customer {
        email
        hasTags(tags: [
          "student_institute:owis-riyadh"
          "student_institute:sek"
          "student_institute:riyadh-schools-malqa"
          "student_institute:riyadh-schools-hittin"
          "student_institute:bisr"
          "student_institute:bisj"
          "student_institute:aisr"
          "student_institute:aldenham"
          "student_institute:king-faisal-school"
          "student_institute:brooke-house"
          "student_institute:pnu"
          "student_institute:alfaisal"
          "student_institute:imamu"
          "student_institute:kau"
          "student_institute:aou"
          "student_institute:kaust"
          "student_institute:mu"
          "student_institute:ksu"
          "student_institute:kfupm"
        ]) {
          tag
          hasTag
        }
      }
    }
    lines {
      id
      quantity
      merchandise {
        __typename
        ... on ProductVariant {
          product {
            ipad: inCollections(ids: ["gid://shopify/Collection/452991221978"]) {
              isMember
            }
            mac: inCollections(ids: ["gid://shopify/Collection/452991746266"]) {
              isMember
            }
            accessories: inCollections(ids: ["gid://shopify/Collection/453527797978"]) {
              isMember
            }
            iphone: inCollections(ids: ["gid://shopify/Collection/452991123674"]) {
              isMember
            }
            appleWatch: inCollections(ids: ["gid://shopify/Collection/52991287514"]) {
              isMember
            }
            tvHome: inCollections(ids: ["gid://shopify/Collection/453560008922"]) {
              isMember
            }
            airpods: inCollections(ids: ["gid://shopify/Collection/453560271066"]) {
              isMember
            }
          }
        }
      }
    }
  }
  discount {
    discountClasses
    metafield(
      namespace: "$app:category-tier-discount-native"
      key: "function-configuration"
    ) {
      value
    }
  }
}
