query CartInput {
  shop {
    localTime {
      macbookNeoOfferActive: dateTimeBetween(
        startDateTime: "2026-06-09T00:00:00"
        endDateTime: "2026-08-10T00:00:00"
      )
    }
  }
  cart {
    buyerIdentity {
      customer {
        metafield(namespace: "$app:student-discount", key: "institute_key") {
          value
        }
      }
    }
    lines {
      id
      quantity
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            collections: inCollections(
              ids: [
                "gid://shopify/Collection/452991221978"
                "gid://shopify/Collection/452991746266"
                "gid://shopify/Collection/453527797978"
                "gid://shopify/Collection/452991123674"
                "gid://shopify/Collection/52991287514"
                "gid://shopify/Collection/453560008922"
                "gid://shopify/Collection/453560271066"
              ]
            ) {
              collectionId
              isMember
            }
          }
        }
      }
    }
  }
  discount {
    discountClasses
    metafield(
      namespace: "$app:category-tier-discount-native"
      key: "function-configuration"
    ) {
      value
    }
  }
}
